INSERT INTO public.media(
	id, auteur, titre, type)
	VALUES 
	(100, 'J.K. Rowling', 'Harry Potter', 'Livre'),
	(101, 'Harper Lee', 'Ne tirez pas sur l oiseau moqueur', 'Livre'),
	(102, 'J.R.R. Tolkien', 'Le Seigneur des Anneaux', 'Livre'),
	(103, 'J.R.R. Tolkien', 'Le Hobbit', 'Livre'),
	(104, 'Jane Austen', 'Orgueil et Préjugés', 'Livre'),
	(105, 'Les Apotres', 'La Bible', 'Livre'),
	(106, 'Douglas Adams', 'Le Guide du voyageur galactique', 'Livre'),
	(107, 'Suzanne Collins', 'Hunger Games', 'Livre'),
	(108, 'J.D. Salinger', 'L Attrape-cœurs', 'Livre'),
	(109, ' C.S. Lewis', 'Les Chroniques de Narnia', 'Livre'),
	
	(110, 'F. Scott Fitzgerald', 'Gatsby le Magnifique', 'Livre'),
	(111, 'George Orwell', '1984', 'Livre'),
	(112, 'Louisa May Alcott', 'Les Quatre Filles du docteur March', 'Livre'),
	(113, 'Charlotte Bronte', 'Jane Eyre', 'Livre'),
	(114, 'Stephen King', 'Le Fléau', 'Livre'),
	(115, 'Margaret Mitchell', 'Autant en emporte le vent', 'Livre'),
	(116, 'Madeleine L Engle', 'Un raccourci dans le temps', 'Livre'),
	(117, 'Margaret Atwood', 'La Servante écarlate', 'Livre'),
	(118, 'C.S. Lewis', 'Le Lion, la Sorcière blanche et l Armoire magique', 'Livre'),
	(119, 'Paulo Coelho', 'L Alchimiste', 'Livre'),
	
	(120, 'L.M. Montgomery', 'Anne... la maison aux pignons verts', 'Livre'),
	(121, 'Lois Lowry', 'Le Passeur', 'Livre'),
	(122, 'Khaled Hosseini', 'Les Cerfs-volants de Kaboul', 'Livre'),
	(123, 'Orson Scott Card', 'La Stratégie Ender', 'Livre'),
	(124, 'Barbara Kingsolver', 'Les Yeux dans les arbres', 'Livre'),
	(125, 'William Golding', 'Sa Majesté des Mouches', 'Livre'),
	(126, 'Robert Jordan', 'L Œil du monde', 'Livre'),
	(127, 'Markus Zusak', 'La Voleuse de livres', 'Livre'),
	(128, 'Emily Bronte', 'Les Hauts de Hurlevent', 'Livre'),
	(129, 'William Shakespeare', 'Hamlet', 'Livre'),
	
	(130, 'Antoine de Saint-Exupery', 'Le Petit Prince', 'Livre'),
	(131, 'Sir Arthur Conan Doyle', 'Sherlock Holmes', 'Livre'),
	(132, 'Ray Bradbury', 'Fahrenheit 451', 'Livre'),
	(133, 'George Orwell', 'La Ferme des Animaux', 'Livre'),
	(134, '?', 'Le Livre de Mormon', 'Livre'),
	(135, 'Anne Frank', 'Le journal d Anne Frank', 'Livre'),
	(136, 'Frank Herbert', 'Dune', 'Livre'),
	(137, 'Gabriel Garcia Marquez', 'Cent ans de solitude', 'Livre'),
	(138, 'Malcolm X', 'L Autobiographie', 'Livre'),
	(139, 'John Steinbeck', 'Des souris et des hommes', 'Livre'),
	
	(140, 'Shel Silverstein', 'L Arbre généreux', 'Livre'),
	(141, 'John Green', 'Nos étoiles contraires', 'Livre'),
	(142, 'Jack Kerouac', 'Sur la route', 'Livre'),
	(143, 'Christopher Moore', 'L agneau', 'Livre'),
	(144, 'Kurt Vonnegut', 'Abattoir 5', 'Livre'),
	(145, 'John Irving', 'Une prière pour Owen', 'Livre'),
	(146, 'Neil Gaiman et Terry Pratchett', 'De bons présages', 'Livre'),
	(147, 'Kathryn Stockett', 'La Couleur des sentiments', 'Livre'),
	(148, 'S.E. Hinton', 'Outsiders', 'Livre'),
	(149, 'Neil Gaiman', 'American Gods', 'Livre')
	;