INSERT INTO public.media(
	id, auteur, titre, type)
	VALUES 
	(5000, 'Francis Cabrel', 'Hors saison', 'CD'),
	(5001, 'Jean-Jacques Goldman', 'Rouge', 'CD'),
	(5002, 'Johnny Hallyday', 'Sang pour sang', 'CD'),
	(5003, 'Patricia Kaas', 'Le mot de passe', 'CD'),
	(5004, 'Axel Red', 'À tâtons', 'CD'),
	(5005, 'Véronique Sanson', 'Symphonique', 'CD'),
	(5006, 'William Sheller', 'Les machines absurdes', 'CD'),
	(5007, 'Alain Souchon', 'Au ras des pâquerettes', 'CD'),
	(5008, 'The Cranberries', 'Bury the hatchet', 'CD'),
	(5009, 'Eurythmics', 'Peace', 'CD'),
	
	(5010, 'Alanis Morissette', 'MTV unplugged', 'CD'),
	(5011, 'Moby', 'Play', 'CD'),
	(5012, 'Santana', 'Supernatural', 'CD'),
	(5013, 'Texas', 'The hush', 'CD'),
	(5014, 'Tina Turner', 'Twenty for seven', 'CD'),
	(5015, 'Tracy Chapman', 'Telling stories', 'CD'),
	(5016, 'Compilations', '100 hits métal', 'CD'),
	(5017, 'Relapse Records', 'Corporate Death', 'CD'),
	(5018, 'Wrong Again', 'W.A.R. Compilation', 'CD'),
	(5019, 'Metallica', 'Kill  Em All', 'CD'),
	
	(5020, 'Metallica', 'Master of Puppets', 'CD'),
	(5021, 'Metallica', 'Metallica', 'CD'),
	(5022, 'Metallica', 'Hardwired… to Self-Destruct', 'CD'),
	(5023, 'Rammstein', 'Mutter', 'CD'),
	(5024, 'Rammstein', 'Reise, Reise ', 'CD'),
	(5025, 'Rammstein', 'Rosenrot', 'CD'),
	(5026, 'Rammstein', 'Sehnsucht', 'CD'),
	(5027, 'Rammstein', 'Herzeleid', 'CD'),
	(5028, 'Rammstein', 'Liebe ist für alle da', 'CD'),
	(5029, 'Muse', 'Showbiz', 'CD'),
	(5030, 'Muse', 'Origin of Symmetry', 'CD'),
	(5031, 'Muse', 'Absolution', 'CD'),
	(5032, 'Muse', 'Black Holes and Revelations', 'CD'),
	(5033, 'Muse', 'The Resistance', 'CD'),
	(5034, 'Muse', 'The 2nd Law', 'CD'),
	(5035, 'Muse', 'Drones', 'CD');